---
- name: Ensure Prometheus directory exists
  file:
    path: /etc/prometheus
    state: directory
    mode: '0755'

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config }}"
    mode: '0644'

- name: Install Prometheus if not present
  apt:
    name: prometheus
    state: present
    update_cache: yes
  register: prometheus_install

- name: Restart Prometheus service
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
  ignore_errors: yes